name: simple-message-logger

services:
  bot:
    build: .
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./config.json:/usr/src/app/config.json
      - ./logs:/usr/src/app/logs
      - data:/usr/src/app/data

volumes:
  data: